language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: lvdKdkMbjqzoLtQ7aNtR482QPfPQwhoO810GDfeYN8x5JM6YFa/6i9KHBitIxx8xrcLdx7QwG68lIuV1GNS5uy4Y0MP0ty+Un4gvuPHf4LtQAruk0K/30dZ7ddp5gkRcL5ykTYO4MEQCK+KMRvrWfbYOsHEpDUnoiKkOgQRUg4gr5b0ilV+dtdUSaK18CuB4gPsdy6UQFnphnJRaGxwZ/UgawA3ypZ3p6XaR21nAWbLl1/XwEw/XqKshlavNl9q7OFE8Ng+gqp55FoR1NCEu0FovG41WPxWiMrBG1KP2APppQUZfpl8KrNuNtwMVnscuBuidznRnoxSo33pacF5htQra8brgjPV6CkFfT/OV3MOMKtzzx3KOFtRNKjOchQFWju1VkAC0+YHTUsnJHyj5GQzDBvo0O0bFGPzOW1OyBpDaB/fBYNuIhhdVGXIBZWbS/ZQY7dMqaftc6VDC4l4S2si7vz4LHhWznI8IcPjGbp5Ev/hF10Iyb5JuZJYr1h/NTzt3P1xVyQHxl0725KQh0fAuDFhZ3s49lVm9UnvN/WRiqpin/f3Zr4lj3XlA5WFOfumEBdALeTVOA5Cei3sNywhX1ZdF+GFdtfC4/7cCLR+Hc48z6tIlAJ5r4J2iSr6yLORM6aWKyzzAfEbit+CP9Edn+vuheUTcFNLsKi+0xP0=
  app: frodo-app
